version: '3.8'

services:
  postgres:
    image: postgres
    container_name: uuid-generator
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - uuid-generator-network

networks:
  uuid-generator-network:

volumes:
  uuid-generator-volume: